name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
env:
  ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
  ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
  USER1_EMAIL: ${{ secrets.USER1_EMAIL }}
  USER1_PASSWORD: ${{ secrets.USER1_PASSWORD }}
  USER2_EMAIL: ${{ secrets.USER2_EMAIL }}
  USER2_PASSWORD: ${{ secrets.USER2_PASSWORD }}
  NOT_USER_EMAIL: ${{ secrets.NOT_USER_EMAIL }}
  NOT_USER_PASSWORD: ${{ secrets.NOT_USER_PASSWORD }}
  INVALID_EMAIL: ${{ secrets.INVALID_EMAIL }}
  INVALID_PASSWORD: ${{ secrets.INVALID_PASSWORD }}
  VALID_REGISTRATION_PASSWORD: ${{ secrets.VALID_REGISTRATION_PASSWORD }}
  INVALID_REGISTRATION_PASSWORD: ${{ secrets.INVALID_REGISTRATION_PASSWORD }}
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
